repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
        exclude: ^tests/fixtures/example-code/invalid-syntax.py$
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^tests/fixtures/diffs/
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: ^
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^(.git|__pycache__|__init__.py|.mypy_cache|.pytest_cache|alembic)
        args: [--exclude=__init__.py, --max-line-length=88]
